micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_SERVER:localhost}:${KEY_MANAGER_PORT:50051}'